# Generated by Django 5.2.6 on 2025-09-11 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_caregory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caregory',
            new_name='Category',
        ),
    ]
